a="Garidipuri Anil Kumar"
print(a.upper())
print(a.lower())
print(a.split())
print(a.islower())
print(a.isupper())
print(a.isalnum())
print(a.isalpha())
print(a.isdigit())
print(a.strip())
print(len(a))
print(a.istitle())
print(a.title())
print(a.capitalize())
print(a.swapcase()) 